#!/usr/bin/env bash
addToPathFront $DENO_INSTALL
addToPath /usr/local/go/bin
addToPath $GOPATH/bin
addToPath $HOME/work/wrapper
addToPath $HOME/.yarn/bin
addToPath /usr/lib/llvm-8/bin
addToPath $HOME/personal/uhh/build
addToPath $HOME/.cargo/bin
addToPath $HOME/.rustup
addToPath /opt/nvim-linux64/bin

# ccache
addToPathFront /usr/lib/ccache
