FROM ubuntu

RUN apt update; apt install python-is-python3 ansible openssh-client vim iputils-ping gpg -y
# COPY ./bootstrap.yml /temp/ansible/bootstrap.yml
# COPY ./secrets.yml /temp/ansible/secrets.yml
